server:
  port: 9999
  path: /hello

person:
  name: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps: {k1: v1, k2: 12} #字符串默认可以不添加引号
  lists:
  - lisi
  - zhaoliu
  dog:
    name: 小狗
    age: 12
  gender: 男,女
# debug: true
# 配置Mysql驱动
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    data-password: root

security:
  user:
    name: root
    password: root
    role: ADMIN
